; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = KMUTNB-ESP32-V1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

[env:KMUTNB-ESP32-V1]
extends = env:esp32-s3-devkitc-1
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.11.0
	; bodmer/TFT_eSPI@^2.5.43
	moononournation/GFX Library for Arduino@^1.6.5
	bblanchon/ArduinoJson@^7.0.0
	lvgl/lvgl@9.0.0
	jakalada/ADXL345@^0.2.0
build_flags = -std=c++17
extra_scripts = pre:scripts/post_install.py

[env:KMUTNB-ESP32-V1-LCD-TESTER]
extends = env:KMUTNB-ESP32-V1
build_src_filter = +<../tools/lcd_tester/> -<src/>

[env:i2c_scanner]
build_src_filter = +<../tools/i2c_scanner/> -<src/>

[env:Touch_calibrate]
extends = env:KMUTNB-ESP32-V1
build_src_filter = +<../tools/Touch_calibrate/> -<src/>

[env:lvgl_touch_calibration]
extends = env:KMUTNB-ESP32-V1
build_src_filter = +<../tools/lvgl_touch_calibration/> -<src/>

[env:new_library_tester]
extends = env:esp32-s3-devkitc-1
lib_deps =
	moononournation/GFX Library for Arduino@1.5.9
build_src_filter = +<../tools/new_library_tester/> -<src/>

; /home/surasak/Documents/PlatformIO/Projects/KMUTNB-1-V2.0-TEST/src/lv_conf.h

; /home/surasak/Documents/PlatformIO/Projects/KMUTNB-ESP32-V2.0-TEST/src/lv_conf.h
